set(_CATKIN_CURRENT_PACKAGE "mobile_robot_sim")
set(mobile_robot_sim_VERSION "0.0.0")
set(mobile_robot_sim_MAINTAINER "roskinetic <roskinetic@todo.todo>")
set(mobile_robot_sim_PACKAGE_FORMAT "2")
set(mobile_robot_sim_BUILD_DEPENDS )
set(mobile_robot_sim_BUILD_EXPORT_DEPENDS )
set(mobile_robot_sim_BUILDTOOL_DEPENDS "catkin")
set(mobile_robot_sim_BUILDTOOL_EXPORT_DEPENDS )
set(mobile_robot_sim_EXEC_DEPENDS )
set(mobile_robot_sim_RUN_DEPENDS )
set(mobile_robot_sim_TEST_DEPENDS )
set(mobile_robot_sim_DOC_DEPENDS )
set(mobile_robot_sim_URL_WEBSITE "")
set(mobile_robot_sim_URL_BUGTRACKER "")
set(mobile_robot_sim_URL_REPOSITORY "")
set(mobile_robot_sim_DEPRECATED "")